### ISSUE TITLE
demo 中的例子，报错了？

### ISSUE THREAD

**Issue by JoMartinezZhu** [duty-os/white-demo-web#6]
![image](https://user-images.githubusercontent.com/43346131/50547679-b6440d00-0c79-11e9-9eee-91ea70296af1.png)

**Comment by leavesster** [comment]
服务端网络请求，需要额外一个 name 参数。
目前 web端的 demo，已经迁移至 [white-demo](https://github.com/duty-os/white-demo) 项目
具体更多 API，可以参考 [开发文档](https://developer.herewhite.com/)
